"""
Cloud SQL (PostgreSQL) - MaaS endpoint parameters
What each endpoint of endpoint_catalog_v1.csv takes in. A DRAFT for the Owner to refine: the catalog itself has
no parameter data. The tenant and the caller always come from the sign-in, never from parameters.

Shorthand, comma separated:   name*:type
  *      required
  :type  id, str (default), text, int, num, bool, date, dt, email, secret, path, file, obj, list, or enum(a|b|c)
"none" means the endpoint takes nothing and returns its data directly.

Lookup order: the full path ("paas/fraud/review/decide") then "feature/sub-category" ("fraud/review/decide").
"""

from typing import Any, Dict, List, Optional

RANGE = "from:date, to:date"
CHAT = "message*:text, session_id:id, language"
VOICE_IN = "audio*:file, session_id:id, language"
CONFIG = "scope:list, tone:enum(formal|friendly|concise), modes:list"
SIGN_IN = "email*:email, password*:secret"
REFRESH = "refresh_token*:secret"
RESET_REQ = "email*:email"
RESET_CONFIRM = "token*, new_password*:secret"
PW_CHANGE = "current_password*:secret, new_password*:secret"
INVITE_ACCEPT = "invite_token*, password*:secret"
FLAG_READ = "status:enum(open|reviewed|closed)"
DECIDE = "case_id*:id, decision*:enum(approve|reject), note"
THRESHOLD = "threshold_name*, value*:num"
IMPACT_BASELINE = "event_type*, baseline_value*:num, unit*"
IMPACT_EVENT = "event_id*:id, saving*:num, unit*"
IMPACT_REPORT_READ = "report_id:id, period"
IMPACT_REPORT_GEN = "period*"
PRICE_ENUM = "price_type*:enum(commission|fixed), rate*:num"

PARAMS: Dict[str, str] = {
    # ---- MaaS: root account
    "root-account/provision": "company_name*, legal_name*, root_mail*:email, industry, location, services*:list",
    "root-account/read": "none",
    "root-account/settings/read": "none",
    "root-account/settings/update": "company_name, contact_mail:email, timezone, default_language, default_currency",
    "root-account/login": SIGN_IN,
    "root-account/logout": "none",
    "root-account/session/refresh": REFRESH,
    "root-account/password/reset/request": RESET_REQ,
    "root-account/password/reset/confirm": RESET_CONFIRM,
    "root-account/password/change": PW_CHANGE,
    "root-account/mail/update": "new_mail*:email, password*:secret",
    # ---- MaaS: roles and mail
    "role/create": "name*, description",
    "role/read": "none",
    "role/update": "role_id*:id, name, description",
    "role/deactivate": "role_id*:id",
    "role/permission/read": "role_id*:id",
    "role/permission/assign": "role_id*:id, endpoint_path*:path",
    "role/permission/revoke": "role_id*:id, endpoint_path*:path",
    "role-mail/list": "none",
    "role-mail/assign": "role_id*:id, mail*:email",
    "role-mail/remove": "role_id*:id, mail*:email",
    "role-mail/invite/send": "role_id*:id, mail*:email",
    "owner-role/create": "name*, description, permissions:list",
    "owner-role/read": "none",
    "owner-role/update": "role_id*:id, name, description, permissions:list",
    "owner-role/deactivate": "role_id*:id",
    "owner-role-mail/list": "none",
    "owner-role-mail/assign": "role_id*:id, mail*:email",
    "owner-role-mail/remove": "role_id*:id, mail*:email",
    "owner-role-mail/invite/send": "role_id*:id, mail*:email",
    "notification/root-mail/send": "event_type*, role_id:id, message*:text",
    "notification/root-mail/log/read": RANGE,
    # ---- MaaS: accounts
    "user/staff/list": "none",
    "user/customer/list": "none",
    "user/customer/read": "customer_id*:id",
    "customer-account/register/individual": "full_name*, email*:email, password*:secret, phone, preferred_language",
    "customer-account/register/business": "business_name*, tax_id*, contact_name*, email*:email, password*:secret, phone",
    "customer-account/login": SIGN_IN,
    "customer-account/logout": "none",
    "customer-account/session/refresh": REFRESH,
    "customer-account/mail/verify": "token*",
    "customer-account/profile/read": "none",
    "customer-account/profile/update": "full_name, phone, address:obj, preferred_language",
    "customer-account/deactivate": "password*:secret, reason",
    "customer-account/password/reset/request": RESET_REQ,
    "customer-account/password/reset/confirm": RESET_CONFIRM,
    "customer-account/password/change": PW_CHANGE,
    "customer-account/data/export": "format:enum(json|csv)",
    "customer-account/data/delete": "password*:secret, reason",
    "staff-account/invite/accept": INVITE_ACCEPT,
    "staff-account/login": SIGN_IN,
    "staff-account/logout": "none",
    "staff-account/session/refresh": REFRESH,
    "staff-account/password/reset/request": RESET_REQ,
    "staff-account/password/reset/confirm": RESET_CONFIRM,
    "staff-account/password/change": PW_CHANGE,
    "owner-account/login": SIGN_IN,
    "owner-account/logout": "none",
    "owner-account/session/refresh": REFRESH,
    "owner-account/invite/accept": INVITE_ACCEPT,
    "owner-account/password/reset/request": RESET_REQ,
    "owner-account/password/reset/confirm": RESET_CONFIRM,
    "owner-account/password/change": PW_CHANGE,
    "assistant/account-help/ask": "question*:text, language",
    # ---- MaaS: data, endpoints, entitlements, keys, versions
    "database/record/read": "collection*, record_id*:id",
    "database/record/write": "collection*, record_id:id, data*:obj",
    "database/export": "collection*, format*:enum(csv|json)",
    "endpoint/purchased/list": "none",
    "endpoint/customer/enable": "endpoint_path*:path",
    "endpoint/customer/disable": "endpoint_path*:path",
    "endpoint/opt-in/request": "endpoint_path*:path, message",
    "endpoint/opt-in/request/read": FLAG_READ.replace("open|reviewed|closed", "open|approved|declined"),
    "service/opt-in/request": "service*:enum(paas|taas|saas), message",
    "consumer/onboard": "company_name*, legal_name*, root_mail*:email, industry, location, services*:list",
    "consumer/entitlement/grant": "consumer_id*:id, endpoint_paths*:list",
    "consumer/entitlement/revoke": "consumer_id*:id, endpoint_paths*:list",
    "api-key/issue": "consumer_id*:id, label, expires_at:dt",
    "api-key/rotate": "key_id*:id",
    "api-key/revoke": "key_id*:id",
    "api-key/list": "none",
    "endpoint-version/publish": "endpoint_path*:path, version*, changelog",
    "endpoint-version/retire": "endpoint_path*:path, version*",
    "endpoint-version/read": "none",
    "service-identity/permission/read": "none",
    "service-identity/permission/assign": "identity*, endpoint_paths*:list",
    "audit/log/write": "endpoint_path*:path, actor_id*:id, action*, at*:dt",
    "audit/log/read": "from:date, to:date, actor_id:id, endpoint_path:path",
    "audit/log/export": "from:date, to:date, format*:enum(csv|json)",
    "audit/owner-log/read": "from:date, to:date, actor_id:id",
    # ---- MaaS: interface, locale, stores
    "interface/template/create": "name*, layout*:obj, branding:obj, sections:list",
    "interface/template/read": "none",
    "interface/template/update": "layout:obj, branding:obj, sections:list",
    "interface/template/role-view/update": "role_id*:id, view*:obj",
    "interface/template/preview": "none",
    "interface/template/publish": "version_note",
    "interaction/mode/settings/update": "text_to_text:bool, text_to_speech:bool, speech_to_text:bool, speech_to_speech:bool",
    "locale/language/set": "languages*:list, default_language*",
    "locale/region/set": "mode*:enum(local|global), regions:list",
    "locale/currency/set": "currencies*:list, default_currency*",
    "locale/language/customer-select": "language*",
    "location/store/create": "name*, address*, city*, country*, latitude:num, longitude:num, opening_hours",
    "location/store/read": "none",
    "location/store/update": "store_id*:id, name, address, city, country, latitude:num, longitude:num, opening_hours",
    "location/store/deactivate": "store_id*:id",
    "location/store/list": "none",
    "location/store/nearby/find": "latitude*:num, longitude*:num, radius_km:num",
    # ---- MaaS: partners and Owner tickets
    "partner/link/list": "none",
    "partner/link/approve": "link_id*:id, " + PRICE_ENUM,
    "partner/link/enable": "link_id*:id",
    "partner/link/disable": "link_id*:id",
    "partner/link/customer-access/enable": "link_id*:id",
    "partner/link/customer-access/disable": "link_id*:id",
    "partner/commission/policy/set": "link_id*:id, " + PRICE_ENUM,
    "partner/commission/usage/read": "link_id*:id, from:date, to:date",
    "partner/call/relay": "link_id*:id, endpoint_path*:path, payload*:obj",
    "partner/call/log/read": "link_id:id, direction:enum(in|out), from:date, to:date",
    "owner-ticket/create/general": "subject*, message*:text, category*:enum(platform|plan|endpoint), priority:enum(low|normal|high)",
    "owner-ticket/create/partner-link": "partner_consumer_id*:id, services*:list, message",
    "owner-ticket/read": "none",
    "owner-ticket/reply/consumer": "ticket_id*:id, message*:text",
    "owner-ticket/reply/owner": "ticket_id*:id, message*:text",
    "owner-ticket/price-settlement/record": "ticket_id*:id, " + PRICE_ENUM,
    "owner-ticket/close": "ticket_id*:id, resolution",
    # ---- MaaS: analytics, billing, impact, fraud
    "analytics/dashboard/read": RANGE,
    "analytics/usage/read": "endpoint_path:path, from:date, to:date",
    "billing/usage/read": "endpoint_path:path, from:date, to:date",
    "billing/invoice/read": "from:date, to:date",
    "fraud/account/detect": "account_id*:id, activity:obj",
    "fraud/account/flag/read": FLAG_READ,
    "fraud/threshold/update": THRESHOLD,
    "fraud/review-queue/read": "none",
    "fraud/review-queue/decide": DECIDE,
    "impact/ledger/read": "service:enum(maas|paas|taas|saas), from:date, to:date",
    "impact/baseline/read": "service:enum(maas|paas|taas|saas)",
    "impact/baseline/method/define": "service*:enum(maas|paas|taas|saas), method*:text",
    "impact/baseline/method/read": "figure_id*:id",
    "impact/report/net/generate": "period*, service:enum(maas|paas|taas|saas)",
    "impact/report/net/read": IMPACT_REPORT_READ,
    "impact/ai-footprint/read": RANGE,
    "impact/source-confidence/read": "figure_id*:id",
    "impact/report/export": "report_id*:id, format*:enum(csv|pdf)",

    # ---- PaaS: catalog and orders
    "catalog/product/create": "name*, description, category_id*:id, sku*, price*:num, currency, condition:enum(new|refurbished|used), images:list, attributes:obj, stock:int",
    "catalog/product/read": "none",
    "catalog/product/view": "product_id*:id",
    "catalog/product/update": "product_id*:id, name, description, category_id:id, price:num, condition:enum(new|refurbished|used), images:list, attributes:obj",
    "catalog/product/archive": "product_id*:id",
    "catalog/category/create": "name*, parent_id:id",
    "catalog/category/update": "category_id*:id, name, parent_id:id",
    "catalog/search/text": "query*, filters:obj, page:int",
    "catalog/search/voice": "audio*:file, language",
    "catalog/search/image": "image*:file",
    "order/cart/add": "product_id*:id, quantity*:int",
    "order/cart/remove": "product_id*:id",
    "order/cart/read": "none",
    "order/checkout/place": "address*:obj, delivery_option_id:id, payment_method*, coupon_code",
    "order/read/customer": "none",
    "order/read/staff": "status:enum(placed|paid|shipped|delivered|cancelled), from:date, to:date",
    "order/cancel/customer": "order_id*:id, reason",
    "order/status/update": "order_id*:id, status*:enum(placed|paid|shipped|delivered|cancelled)",
    "offline-sale/record": "store_id*:id, items*:list, payment_method*, customer_id:id",
    "payment/gateway/process": "order_id*:id, amount*:num, currency*, payment_method*:obj",
    "payment/invoice/read": "order_id*:id",
    "promotion/coupon/create": "code*, discount_type*:enum(percent|fixed), value*:num, valid_from:date, valid_to:date, usage_limit:int",
    "promotion/coupon/deactivate": "coupon_id*:id",
    "promotion/coupon/apply": "code*, order_id:id",
    "wishlist/item/add": "product_id*:id",
    "wishlist/item/remove": "product_id*:id",
    "wishlist/read": "none",
    # ---- PaaS: stock, lifecycle, passport, parts
    "inventory/stock/read": "sku, store_id:id",
    "inventory/stock/update": "sku*, store_id:id, quantity*:int",
    "inventory/stock/adjust": "sku*, quantity_change*:int, reason*:enum(damage|loss|correction)",
    "inventory/low-stock/alert": "sku*, store_id:id, quantity*:int, threshold*:int",
    "store-stock/read": "product_id*:id",
    "lifecycle/record/create": "item_id*:id, source*, condition",
    "lifecycle/record/read": "item_id*:id",
    "lifecycle/state/update": "item_id*:id, state*",
    "passport/generate": "item_id*:id",
    "passport/read": "passport_id*:id",
    "passport/scan": "qr_code*",
    "passport/ownership/transfer": "passport_id*:id, new_owner_id*:id",
    "parts/listing/create": "name*, source_item_id:id, price*:num, quantity*:int, condition",
    "parts/listing/read": "query, category",
    # ---- PaaS: bidding
    "bid/rules/ai-limits/set": "min_price*:num, max_discount_pct*:num, max_rounds:int",
    "bid/rules/price-limits/set": "category_id:id, floor*:num, ceiling*:num",
    "bid/rules/window/set": "duration_hours*:int",
    "bid/rules/seller-eligibility/set": "min_rating:num, min_stock:int, regions:list",
    "bid/ai/start": "product_id*:id, offer_price*:num",
    "bid/ai/counter-offer/send": "bid_id*:id, price*:num, message",
    "bid/ai/customer-reply": "bid_id*:id, action*:enum(accept|counter|decline), price:num",
    "bid/ai/counter-offer/voice": "bid_id*:id, audio*:file",
    "bid/ai/finalize/handoff": "bid_id*:id, final_price*:num",
    "bid/ai/decision/accept": "bid_id*:id",
    "bid/ai/decision/reject": "bid_id*:id, reason",
    "bid/human/start": "product_id*:id, offer_price*:num",
    "bid/human/offer/respond": "bid_id*:id, response*:enum(accept|counter|reject), price:num, message",
    "bid/human/counter/customer": "bid_id*:id, price*:num",
    "bid/human/accept": "bid_id*:id",
    "bid/human/reject": "bid_id*:id, reason",
    "bid/multi-seller/open": "description*, quantity*:int, max_price:num, location, condition:enum(new|refurbished|used), deadline:dt",
    "bid/multi-seller/seller-match": "request_id*:id",
    "bid/multi-seller/offer/submit": "request_id*:id, price*:num, delivery_days*:int, condition*:enum(new|refurbished|used)",
    "bid/multi-seller/rank/read": "request_id*:id",
    "bid/multi-seller/award": "request_id*:id",
    "bid/guardrail/anomaly/detect": "bid_id*:id",
    "bid/guardrail/review/decide": "bid_id*:id, decision*:enum(approve|reject), note",
    "auction/surplus/open": "product_id*:id, quantity*:int, start_price*:num, ends_at*:dt",
    "auction/surplus/bid": "auction_id*:id, amount*:num",
    "auction/surplus/close": "auction_id*:id",
    # ---- PaaS: forecasting, pricing, rebalancing, trust
    "forecast/demand/run": "sku, store_id:id, horizon_days:int",
    "forecast/demand/read": "sku, store_id:id",
    "forecast/reorder/suggest": "sku*, store_id:id",
    "forecast/reorder/approve": "suggestion_id*:id, quantity:int",
    "pricing/dynamic/rules/set": "min_margin_pct*:num, max_change_pct*:num, factors:list",
    "pricing/dynamic/suggest": "product_id*:id",
    "pricing/dynamic/apply": "suggestion_id*:id",
    "pricing/shelf-life-decay/apply": "product_id*:id, expiry_date*:date",
    "pricing/personalized/offer/read": "product_id*:id",
    "stock-rebalance/proposal/generate": "sku*, from_location:id",
    "stock-rebalance/proposal/accept": "proposal_id*:id",
    "stock-rebalance/proposal/reject": "proposal_id*:id, reason",
    "seller-trust/score/update": "seller_id*:id, event*, delta:num",
    "seller-trust/score/read": "seller_id*:id",
    # ---- PaaS: recommendations, explanation, assistant, personalization
    "recommendation/product/read": "product_id:id, limit:int",
    "recommendation/sustainable/read": "product_id*:id",
    "explain/decision/read": "decision_id*:id",
    "assistant/config/update": CONFIG,
    "assistant/chat/text-to-text": CHAT,
    "assistant/chat/text-to-speech": CHAT + ", voice",
    "assistant/voice/speech-to-text": VOICE_IN,
    "assistant/voice/speech-to-speech": VOICE_IN + ", voice",
    "personalization/limits/set": "enabled_signals:list, retention_days:int",
    "personalization/profile/build": "customer_id*:id",
    "personalization/profile/reset": "none",
    "personalization/display/render": "customer_id*:id, page*",
    "return-risk/checkout/guidance/read": "product_id*:id, size, device_model",
    "future-value/quote/read": "product_id*:id, years:int",
    "future-value/guarantee/issue": "order_id*:id, product_id*:id",
    "future-value/guarantee/redeem": "guarantee_id*:id",
    "trade-in/nudge/send": "customer_id*:id, product_id*:id",
    # ---- PaaS: environment, credits, insights, fraud, baskets, segments, pickup
    "environment/origin/submit": "product_id*:id, materials*:list, process*, country*",
    "environment/origin/verify": "product_id*:id",
    "environment/score/calculate": "product_id*:id",
    "environment/score/read": "product_id*:id",
    "environment/offer-score/read": "offer_id*:id",
    "environment/recycling-factor/read": "product_id*:id",
    "green-credits/rules/set": "earn_per_unit*:num, redeem_value*:num",
    "green-credits/earn": "customer_id*:id, amount*:int, reason*",
    "green-credits/balance/read": "none",
    "green-credits/redeem": "credits*:int, order_id:id",
    "insights/behavior/read": "segment, from:date, to:date",
    "insights/feedback/sentiment/read": "product_id:id, from:date, to:date",
    "feedback/review/submit": "product_id*:id, order_id:id, rating*:int, comment",
    "feedback/review/read": "product_id*:id",
    "fraud/order/detect": "order_id*:id",
    "fraud/order/flag/read": FLAG_READ,
    "fraud/review/decide": DECIDE,
    "basket/frequently-bought/read": "product_id*:id",
    "basket/bundle/suggest": "product_id*:id",
    "basket/bundle/create": "name*, product_ids*:list, price*:num",
    "segment/generate": "criteria:obj",
    "segment/read": "segment_id:id",
    "segment/offer/send": "segment_id*:id, offer*:obj",
    "reserve/item/create": "product_id*:id, store_id*:id, pickup_by:dt",
    "reserve/item/read": "none",
    "reserve/item/cancel": "reservation_id*:id",
    "pickup/store/select": "order_id*:id, store_id*:id",
    "pickup/handover/code/generate": "order_id*:id",
    "pickup/handover/code/verify": "order_id*:id, code*",
    "pickup/handover/mark-collected": "order_id*:id",
    "locale/listing/translate": "product_id*:id, target_language*",
    "locale/price/currency-convert": "amount*:num, from_currency*, to_currency*",
    "analytics/sales/read": "from:date, to:date, group_by:enum(day|week|month|category)",
    "paas/impact/baseline/record": IMPACT_BASELINE,
    "paas/impact/event/record": IMPACT_EVENT,
    "paas/impact/report/read": IMPACT_REPORT_READ,
    "paas/impact/report/generate": IMPACT_REPORT_GEN,
    "paas/impact/rebound/estimate": "period*",

    # ---- TaaS
    "delivery/rules/set": "options*:list, cutoff_time, regions:list",
    "delivery/option/list": "destination_postcode*",
    "delivery/option/select": "order_id*:id, option_id*:id",
    "delivery/window/select": "order_id*:id, window_start*:dt, window_end*:dt",
    "delivery/pricing/dynamic/suggest": "order_id*:id",
    "delivery/pricing/dynamic/apply": "suggestion_id*:id",
    "shipment/create": "order_id*:id, carrier, option_id:id",
    "shipment/read/staff": "status:enum(created|in_transit|delivered|cancelled), from:date, to:date",
    "shipment/status/update": "shipment_id*:id, status*:enum(created|in_transit|delivered|cancelled)",
    "shipment/cancel": "shipment_id*:id, reason",
    "tracking/read": "order_id*:id",
    "tracking/notification/send": "shipment_id*:id, event*",
    "route/shortest/calculate": "origin*:obj, destination*:obj",
    "route/green/recommend": "origin*:obj, destination*:obj, weight_kg:num",
    "route/green/select": "recommendation_id*:id",
    "route/green/explain": "recommendation_id*:id",
    "route/green/impact": "shipment_id*:id, route_id*:id",
    "route/optimize/recommend": "shipment_id*:id, objective:enum(shortest|fastest|cheapest|greenest), stops:list",
    "vehicle/recommend": "shipment_id*:id, weight_kg:num, volume_l:num",
    "delivery/eta/predict": "shipment_id*:id",
    "delivery/slot/recommend": "shipment_id*:id, from:date",
    "taas/explain/decision/read": "decision_id*:id",
    "recommendation/accept": "decision_id*:id",
    "recommendation/override": "decision_id*:id, choice*, reason*:text",
    "carbon/footprint/delivery/read": "order_id*:id",
    "carbon/footprint/offer/read": "offer_id*:id",
    "environment/transport-score/read": "transport_mode*",
    "reverse/route/recommend": "return_id*:id",
    "reverse/route/resale/assign": "return_id*:id",
    "reverse/route/refurbish/assign": "return_id*:id",
    "reverse/route/donate/assign": "return_id*:id",
    "reverse/route/parts/assign": "return_id*:id",
    "reverse/route/recycle/assign": "return_id*:id",
    "reverse/pickup/request": "return_id*:id, address*:obj, preferred_date:date",
    "reverse/pickup/schedule": "return_id*:id, pickup_at*:dt, carrier",
    "reverse/dropoff/store/leg/assign": "return_id*:id, store_id*:id",
    "pickup/store-leg/assign": "order_id*:id, store_id*:id",
    "peer-forward/match": "return_id*:id",
    "peer-forward/ship": "match_id*:id, tracking_code",
    "peer-forward/confirm": "match_id*:id",
    "transfer/stock/create": "sku*, quantity*:int, from_location*:id, to_location*:id",
    "transfer/stock/status/update": "transfer_id*:id, status*:enum(created|in_transit|received)",
    "transfer/stock/receive": "transfer_id*:id, quantity_received:int",
    "refurbisher/shipment/create": "item_id*:id, refurbisher_id*:id",
    "partner/transport/enable": "link_id*:id",
    "partner/transport/offer": "link_id*:id, regions:list",
    "partner/shipment/relay": "shipment_id*:id, link_id*:id",
    "assistant/delivery/text-to-text": CHAT,
    "assistant/delivery/text-to-speech": CHAT + ", voice",
    "assistant/delivery/speech-to-text": VOICE_IN,
    "assistant/delivery/speech-to-speech": VOICE_IN + ", voice",
    "personalization/delivery-options/display": "customer_id*:id, order_id:id",
    "fraud/delivery/anomaly/detect": "shipment_id*:id, event*",
    "taas/fraud/review/decide": DECIDE,
    "locale/service-area/set": "mode*:enum(local|global), regions*:list",
    "locale/address/validate": "address*:obj, country*",
    "locale/notification/language/send": "customer_id*:id, event*, language*",
    "insights/delivery/read": RANGE,
    "analytics/delivery/read": RANGE,
    "taas/impact/baseline/record": "route_id*:id, default_mode*, baseline_value*:num",
    "taas/impact/report/read": IMPACT_REPORT_READ,
    "taas/impact/report/generate": IMPACT_REPORT_GEN,

    # ---- SaaS
    "ticket/create/query": "subject*, message*:text, order_id:id",
    "ticket/create/return": "order_id*:id, product_id*:id, reason*, description",
    "ticket/create/repair": "order_id*:id, product_id*:id, issue*, description",
    "ticket/create/trade-in": "product_id*:id, condition*, description",
    "ticket/read/customer": "none",
    "ticket/read/staff": "status:enum(open|in_progress|resolved|closed), assignee_id:id",
    "ticket/reply/customer": "ticket_id*:id, message*:text",
    "ticket/reply/staff": "ticket_id*:id, message*:text, author",
    "ticket/assign": "ticket_id*:id, assignee_id*:id",
    "ticket/status/update": "ticket_id*:id, status*:enum(open|in_progress|resolved|closed)",
    "ticket/escalate": "ticket_id*:id, reason*",
    "ticket/close": "ticket_id*:id, resolution",
    "ticket/status/read": "ticket_id*:id",
    "return/policy/set": "window_days*:int, conditions:list, refund_method*:enum(original|credit)",
    "return/request/create": "order_id*:id, product_id*:id, reason*, photos:list",
    "return/request/read": "status:enum(requested|approved|rejected|refunded)",
    "return/request/approve": "return_id*:id",
    "return/request/reject": "return_id*:id, reason*",
    "return/refund/issue": "return_id*:id, amount*:num, method",
    "repair/policy/set": "warranty_days*:int, covered_issues:list",
    "repair/request/create": "order_id*:id, product_id*:id, issue*",
    "repair/status/update": "repair_id*:id, status*:enum(received|in_repair|ready|returned), note",
    "triage/return/route": "return_id*:id",
    "grading/threshold/set": "grade*, min_score*:num",
    "grading/photo/submit": "return_id*:id, photos*:list",
    "grading/photo/analyze": "return_id*:id, photo_ids:list",
    "grading/result/read": "return_id*:id",
    "grading/result/override": "return_id*:id, grade*, reason*",
    "saas/trade-in/request/create": "product_id*:id, condition*, photos:list",
    "trade-in/valuation/read": "trade_in_id*:id",
    "trade-in/offer/accept": "trade_in_id*:id",
    "trade-in/process/complete": "trade_in_id*:id, final_value:num",
    "recycling/lifespan/estimate": "item_id*:id",
    "recycling/recyclable-share/estimate": "item_id*:id",
    "recycling/request/create": "item_id*:id, method*:enum(pickup|dropoff)",
    "recycling/handover/record": "recycling_id*:id, recycler_id*:id, weight_kg:num",
    "recycling/certificate/issue": "recycling_id*:id",
    "recommendation/reuse/read": "item_id*:id",
    "recommendation/recycle/read": "item_id*:id",
    "saas/explain/decision/read": "decision_id*:id",
    "parts/harvest/assess": "item_id*:id",
    "refurbisher/profile/register": "name*, skills*:list, capacity*:int, location*",
    "refurbisher/match/run": "item_id*:id",
    "refurbisher/bid/submit": "work_id*:id, price*:num, days*:int",
    "refurbisher/assign": "work_id*:id, refurbisher_id*:id",
    "dispute/open": "order_id*:id, reason*, description*:text, evidence:list",
    "dispute/respond": "dispute_id*:id, message*:text",
    "dispute/resolve": "dispute_id*:id, outcome*:enum(upheld|rejected|settled), note",
    "dispute/trust-score/feed": "dispute_id*:id, seller_id*:id, outcome*",
    "assistant/support/text-to-text": CHAT,
    "assistant/support/text-to-speech": CHAT + ", voice",
    "assistant/support/speech-to-text": VOICE_IN,
    "assistant/support/speech-to-speech": VOICE_IN + ", voice",
    "fraud/return/screen": "return_id*:id",
    "fraud/return/flag/read": FLAG_READ,
    "saas/fraud/review/decide": DECIDE,
    "scorecard/customer/read": "none",
    "scorecard/consumer/read": RANGE,
    "insights/ticket-sentiment/read": RANGE,
    "analytics/support/read": RANGE,
    "dropoff/store/create": "type*:enum(return|repair|trade-in), order_id*:id, product_id*:id, store_id*:id",
    "dropoff/store/receive/code-verify": "dropoff_id*:id, code*",
    "dropoff/store/receive/mark-received": "dropoff_id*:id",
    "dropoff/status/read": "dropoff_id*:id",
    "personalization/ticket-view/display": "customer_id*:id, ticket_id*:id",
    "locale/ticket/translate": "ticket_id*:id, target_language*",
    "locale/policy/region/set": "region*, window_days*:int, refund_method:enum(original|credit)",
    "partner/support/enable": "link_id*:id",
    "partner/issue/relay": "ticket_id*:id, link_id*:id, summary*:text",
    "partner/issue/status/read": "ticket_id*:id",
    "saas/impact/baseline/record": "item_id*:id, landfill_kg*:num",
    "saas/impact/event/record": IMPACT_EVENT,
    "saas/impact/report/read": IMPACT_REPORT_READ,
    "saas/impact/report/generate": IMPACT_REPORT_GEN,
}

_TYPES = {"id", "str", "text", "int", "num", "bool", "date", "dt", "email", "secret", "path", "file", "obj", "list"}

def _parse(spec: str) -> List[Dict[str, Any]]:
    if spec.strip() == "none":
        return []
    params = []
    # commas inside enum(...) are not used, so a plain split is safe
    for token in spec.split(","):
        name, _, kind = token.strip().partition(":")
        required = name.endswith("*")
        kind = kind or "str"
        values = None
        if kind.startswith("enum(") and kind.endswith(")"):
            values, kind = kind[5:-1].split("|"), "enum"
        elif kind not in _TYPES:
            raise ValueError(f"Unknown parameter type {kind!r} in {spec!r}")
        params.append({"name": name.rstrip("*"), "type": kind, "required": required,
                       **({"values": values} if values else {})})
    return params

def parameters_for(path: str) -> Optional[List[Dict[str, Any]]]:
    """The parameters of one endpoint path such as /paas/fraud/review/decide/v1, or None when none are drafted."""
    parts = path.strip("/").split("/")
    full = "/".join(parts[:-1])          # drop the version
    short = "/".join(parts[1:-1])        # drop the service too
    spec = PARAMS.get(full, PARAMS.get(short))
    return None if spec is None else _parse(spec)
